### ISSUE TITLE
error in line 40

### ISSUE THREAD

**Issue by sahilchauhang** [vipul-sharma20/gesture-opencv#13]
File "E:/Project/hand gesture/sample2.py", line 40, in <module>
    cnt = max(contours, key = lambda x: cv2.contourArea(x))

NameError: name 'contours' is not defined

**Comment by devbhartra** [comment]
@sahilchauhang  I am facing the exact same issue. Were you able to fix it?
This is what i got:


Traceback (most recent call last):
  File "gesture.py", line 40, in <module>
    cnt = max(contours, key = lambda x: cv2.contourArea(x))
NameError: name 'contours' is not defined

**Comment by vipul-sharma20** [comment]
@devbhartra Are you using OpenCV 4.x? Because that's the only way you might not be able to get into any of these conditions: https://github.com/vipul-sharma20/gesture-opencv/blob/master/gesture.py#L32-L38 and hence the `NameError` 

I might not be able to fix this right now but, can you please check how `findContours` method works for this new version (most probably it should be like the one in version 3) and update the conditions and run the code? That should do the trick

If you like you can also send a PR :)

**Comment by devbhartra** [comment]
@vipul-sharma20 Yes that was the issue. 
I just changed this:

 if version == '3':
        image, contours, hierarchy = cv2.findContours(thresh1.copy(), \
               cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
    **elif version == '4':**
       contours, hierarchy = cv2.findContours(thresh1.copy(),cv2.RETR_TREE, \
               cv2.CHAIN_APPROX_NONE)

It works now, thanks
